Temp1, Temp2 Temp3 e Temp4 s√£o temperaturas medidas em diferentes partes da planta
Target representa o estado da qualidade da amostra (temp1, temp2, temp3 e temp4)

In [8]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt


#p1_data_test_df = pd.read_csv('p1_data_test.csv',header=0)
df = pd.read_csv('../p1_data_train.csv',header=0)

print df.size
new_df = df[df.index > 2000]
new_df

26045

          Temp1      Temp2      Temp3      Temp4  target
2001  40.964613  17.398179  43.731425  34.425575       0
2002  33.628860  41.420897  45.759518  41.725283       1
2003  32.255840  42.243569  22.782513  26.324182       0
2004  29.004724  34.036788  25.126154  37.318799       0
2005  24.461146  39.424746  42.750307  40.181506       1
2006  39.601662  42.049003  50.549222  45.559827       1
2007  40.438107  34.085394  37.285331  27.005957       0
2008  40.434756  33.935837  51.598718  33.463613       0
2009  34.587714  28.810558  47.275885  26.841295       0
2010  29.005883  38.448550  33.350161  25.980429       0
2011  35.527061  49.677680  39.586829  41.096135       1
2012  39.754278  56.346007  34.914574  51.969998       1
2013  33.172447  31.418113  38.849995  25.485007       0
2014  31.500946  30.434749  27.934729  51.557476       1
2015  34.296364  36.634856  20.159353  41.979907       1
2016  42.505425  37.217242  42.252493  41.972199       1
2017  42.321848  48.320622  45.254177  47.290214       1
2018  31.864484  44.399995  40.046502  40.788764       1
2019  30.251835  25.978611  21.371827  26.780547       0
2020  37.330117  21.461271  38.340100  24.953248       0
2021  34.481539  31.178531  43.000000  35.257340       0
2022  32.849650  30.539512  33.197087  36.982819       1
2023  35.784853  30.212598  32.054839  30.576619       0
2024  35.798447  34.278835  37.319718  36.048971       0
2025  40.990969  34.657075  44.855490  29.362333       1
2026  27.825649  37.745664  26.559619  29.156588       0
2027  31.954876  29.967467  35.421674  27.241570       0
2028  43.533051  41.246722  41.947275  35.994337       1
2029  47.036691  14.053095  38.686584  27.005304       0
2030  27.873674  26.121875  31.769171  37.370044       0
...         ...        ...        ...        ...     ...
5179  39.186606  26.138079  36.779283  29.303698       0
5180  49.431645  30.490756  37.868250  21.961549       0
5181  24.710723  20.293734  15.651789  25.645608       0
5182  51.529853  38.557298  39.533458  27.755264       0
5183  34.670901  12.703905  34.197874  31.818578       0
5184  47.544957  30.804859  32.729223  33.127107       0
5185  34.836260  24.360650  35.240417  30.445009       0
5186  48.361894  44.808955  36.919842  37.582415       1
5187  41.040494  35.294131  36.603095  26.219766       0
5188  26.482798  22.372189  30.155809  32.012882       0
5189  30.428677  53.446034  26.935802  47.066130       1
5190  44.338928  38.721892  40.044447  36.849432       1
5191  40.705855  27.233661  47.061109  32.443130       0
5192  46.206728  26.890741  40.386153  38.856098       0
5193  36.302187  39.213925  22.715638  49.130761       1
5194  27.000655  31.295161  29.423480  30.652046       0
5195  33.657666  20.004207  28.791446  27.317317       0
5196  32.500665  44.517841  27.079064  35.821837       1
5197  40.911587  34.939695  37.855141  37.922647       1
5198  36.580228  28.063964  38.417694  35.074030       0
5199  34.165743  39.588449  34.505612  33.125890       1
5200  27.522591  34.427625  29.448282  24.417261       0
5201  39.797864  39.548852  44.503485  46.462310       1
5202  40.871957  40.268328  38.439344  46.964650       1
5203  38.008263  43.618857  30.900445  41.194809       1
5204  35.810039  40.808990  36.789912  37.555780       1
5205  43.065104  36.784739  53.019730  47.929034       1
5206  33.025842  46.658817  20.536894  40.757932       1
5207  33.678864  46.705067  42.336115  32.714649       1
5208  48.835906  42.847292  43.775250  41.831867       1

[3208 rows x 5 columns]

In [2]:
def get_outliers_index(df, columns, gama = 1.5):
    index_to_drop = []
    for column in columns:
        q2 = df[column].median()
        q3 = df[df[column] > q2][column].median()
        q1 = df[df[column] < q2][column].median()

        IQR = q3 - q1

        index_to_drop += list(df[(df[column] > q3 + gama*IQR) | (df[column] < q1 - gama*IQR)][column].index.values)

    return list(np.unique(index_to_drop))

In [4]:
df.head()


index_to_drop = get_outliers_index(df,['Temp1','Temp2','Temp3','Temp4'])
print df.shape
print len(index_to_drop)
print index_to_drop
df = df.drop(df.index[index_to_drop])
print df.shape

(5209, 5)
59
[13, 29, 92, 117, 125, 263, 434, 474, 527, 645, 660, 693, 699, 711, 822, 823, 889, 1006, 1043, 1100, 1440, 1496, 1515, 1564, 1567, 1573, 1714, 1983, 2090, 2149, 2422, 2450, 2454, 2667, 2738, 2892, 2980, 3006, 3037, 3081, 3176, 3300, 3311, 3374, 3380, 3450, 3733, 3795, 3883, 4014, 4095, 4185, 4413, 4625, 4782, 4786, 4925, 4949, 5112]
(5150, 5)

In [ ]:
data = {'name': ['Jason', 'Molly', 'Tina', 'Jake', 'Amy'],
        'year': [2012, 2012, 2013, 2014, 2014],
        'reports': [4, 24, 31, 2, 3]}
df = pd.DataFrame(data, index = ['Cochice', 'Pima', 'Santa Cruz', 'Maricopa', 'Yuma'])
df
df.drop(df.index[[0,1,2]])

17